{"uuid": "3b1f6192-12ca-4e72-a811-5a96847937c4", "children": ["1fc17070-9166-4130-8986-692b0b909d55", "0c056ed9-9dc1-4656-b474-90e12d749927"], "befores": [{"name": "record", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [WinError 2] 系统找不到指定的文件。\n", "trace": "  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\pluggy\\callers.py\", line 187, in _multicall\n    res = hook_impl.function(*args)\n  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 964, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"c:\\testtools\\python\\python37\\lib\\site-packages\\_pytest\\fixtures.py\", line 788, in call_fixture_func\n    res = next(it)\n  File \"C:\\Users\\heli\\PycharmProjects\\diy_appium\\scripts\\conftest.py\", line 20, in record\n    p = subprocess.Popen(cmd, shell=False, stdout=subprocess.PIPE, stderr=subprocess.STDOUT)\n  File \"c:\\testtools\\python\\python37\\lib\\subprocess.py\", line 800, in __init__\n    restore_signals, start_new_session)\n  File \"c:\\testtools\\python\\python37\\lib\\subprocess.py\", line 1207, in _execute_child\n    startupinfo)\n"}, "start": 1592386294194, "stop": 1592386294201}], "start": 1592386294194, "stop": 1592386294317}